name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 关键！给 gh-pages 分支写权限

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # 如果你的 index.html 就在根目录
          publish_branch: gh-pages
          force_orphan: true  # 创建干净分支
